# Default image (https://hub.docker.com/r/mcserep/php)
image: mcserep/php:7.4

# Stages: lint -> test -> deploy
stages:
  - lint
  - test
  - deploy

# Cached files between builds
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/

# Dependency scanning
include:
  - template: Dependency-Scanning.gitlab-ci.yml

.test:
  # Variables
  variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_USER: tms
    MYSQL_PASSWORD: tms
    MYSQL_DATABASE: tms
    MYSQL_ROOT_PASSWORD: v7tqfR9U
    # Enable code coverage for Xdebug
    XDEBUG_MODE: develop,coverage

  # Executed before every job
  before_script:
  # Run Composer
  - composer install --prefer-dist --no-ansi --no-interaction
  # Configure application
  - cp -f config/db.sample.php config/db.php
  - cp -f config/test_db.gitlab-ci.php config/test_db.php
  - cp -f config/mailer.sample.php config/mailer.php
  - cp -f config/params.sample.php config/params.php
  # Initialize application
  - php tests/bin/yii migrate --interactive=0

  # Services: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
  # Examples: http://docs.gitlab.com/ce/ci/services/README.html
  services:
    - mariadb:10.4

# PHPCS linter
phpcs:
  stage: lint
  before_script:
    # Run Composer
    - composer install --prefer-dist --no-ansi --no-interaction
  script:
    - vendor/bin/phpcs -n --report=full
  allow_failure: true

# Codeception tests & coverage reports
# PHP 7.4
codecept_7.4:
  stage: test
  extends: .test
  image: mcserep/php:7.4
  script:
    - vendor/bin/codecept run unit,api --no-ansi --coverage --coverage-text
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

# Deployment over SSH
.deploy:
  stage: deploy
  image: ubuntu:20.04
  variables:
    DEPLOY_PATH: /var/www/html
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

# Deployment to staging environment of ELTE
# All pushes on develop
deploy_staging:
  extends: .deploy
  variables:
    DEPLOY_PATH: /var/www/tms_dev/backend-core/
  script:
    - ssh-add <(echo "$CD_PRIVATE_KEY")
    - |
      ssh -p22 gitlab-deployer@tms.inf.elte.hu << CMD
        set -e
        set -x
        umask 002
        cd $DEPLOY_PATH
        git status
        git pull
        composer install --prefer-dist --no-ansi --no-interaction
        ./yii migrate --interactive=0
      CMD
  environment:
    name: staging
    url: https://tms.inf.elte.hu/dev-api/
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop" && $CI_PROJECT_NAMESPACE == "tms-elte"'

# Deployment to production environment of ELTE
# All v* tags, excluding prereleases
deploy_production:
  extends: .deploy
  variables:
    DEPLOY_PATH: /var/www/tms/backend-core/
  script:
    - ssh-add <(echo "$CD_PRIVATE_KEY")
    - |
      ssh -p22 gitlab-deployer@tms.inf.elte.hu << CMD
        set -e
        set -x
        umask 002
        cd $DEPLOY_PATH
        git status
        git fetch origin
        git checkout tags/$CI_COMMIT_TAG
        composer install --prefer-dist --no-ansi --no-interaction
        ./yii migrate --interactive=0
      CMD
  environment:
    name: production
    url: https://tms.inf.elte.hu/api/
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v.*$/ && $CI_PROJECT_NAMESPACE == "tms-elte"'
