<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Available from' => 'Elérhető ettől',
    'Automated submission test ready' => 'Beadandó tesztelés elkészült',
    'Automated testing on your previously submitted solution is ready.' => 'A beküldött megoldásod tesztelésre került.',
    'Canvas synchronization errors' => 'Canvas-szinkronizációs hibák',
    'Category' => 'Kategória',
    'Classwork tasks' =>  'Órai munkák',
    'Course' => 'Kurzus',
    'Corrupted' => 'Sérült',
    'Corrupted Submission' => 'Sérült feltöltés',
    'View solution' => 'Megoldás megtekintése',
    'Exams' => 'Vizsgafeladatok',
    'Examinations' => 'Vizsgák',
    'Grade' => 'Értékelés',
    'Graded submission' => 'Beadandó értékelés',
    'Group Number' => 'Csoportszám',
    'Hard deadline of task' => 'Feladat végső határideje',
    'If it was you, please click the following link to confirm the address: {link}' =>
        'Ha te voltál, kattints a következő hivatkozásra a cím megerősítéséhez: {link}',
    'If it wasn’t you, you may disregard this email.' =>
        'Ha nem te voltál, nyugodtan hagyd figyelmen kívül ezt az e-mailt.',
    'Larger tasks' => 'Beadandók',
    'Modifier' => 'Módosító',
    'Name' => 'Név',
    'New grade for previous submission has been recorded.' => 'Új beadandó értékelés került rögzítésre.',
    'Added to new group' => 'Új csoport hozzárendelés',
    'New Canvas synchronization errors have occurred' => 'Új Canvas-szinkronizációs hibák történtek',
    'Added to new course' => 'Új kurzus hozzárendelés',
    'New task' => 'Új feladat kiírás',
    'New task was assigned to the course {course} (group: {group}).' => 'Új feladat került kiírásra a(z) {course} (csoport: {group}) kurzushoz.',
    'New task was assigned to the course {course}.' => 'Új feladat került kiírásra a(z) {course} kurzushoz.',
    'Please confirm your custom email address' => 'Egyedi e-mail-cím megerősítése',
    'Remark' => 'Megjegyzés',
    'Result' => 'Eredmény',
    'Smaller tasks' => 'Házi feladatok',
    'Soft deadline of task' => 'Feladat pótolható határideje',
    'Solution' => 'Megoldás',
    'Someone, probably you, added this email address to the account of {name} in the Task Management System.' =>
        'Valaki, valószínűleg te, hozzáadta ezt az e-mail-címet {name} fiókjához a Beadandó Kezelő Rendszerben.',
    'Status' => 'Státusz',
    'Student solutions submitted in the past {hours} hours' => 'Az elmúlt {hours} órában beküldött új hallgatói megoldások',
    'Submitted solutions' => 'Beküldött megoldások',
    'Task Management System' => 'Beadandókezelő rendszer',
    'Task description' => 'Feladat leírása',
    'Task name' => 'Feladat neve',
    'The list does not contain the already graded solutions.' => 'A lista nem tartalmazza a már értékelt megoldásokat.',
    'You have been assigned to the course {course} (group: {group}).' => 'Hozzárendelésre kerültél a(z) {course} (csoport: {group}) kurzushoz.',
    'You have been assigned to the course {course}.' => 'Hozzárendelésre kerültél a(z) {course} kurzushoz.',
    'You have been assigned to a course.' => 'Hozzárendeltek egy kurzushoz.',
    'You have been assigned to the course {course} as a lecturer.' => 'Hozzárendeltek a {course} kurzushoz előadóként.',
    'You were removed from a group' => 'Eltávolítottak egy csoportból',
    'group' => 'csoport',
    'Your submitted file to Canvas is corrupted.' => 'A Canvasra feltöltött fájlja sérült.',
    'Task deadline change' => 'Feladat határidő változás',
    'The deadline of task {task} for the course {course} (group: {group}) was modified.' => 'Megváltozott a {course} (csoport: {group}) kurzushoz tartozó {task} feladat határideje.',
    'The deadline of task {task} for the course {course} was modified.' => 'Megváltozott a {course} kurzushoz tartozó {task} feladat határideje.',
    'Oncoming submission deadlines' => 'Közelgő beadandó-határidők',
    'You have due submissions with deadline in the next {days} days:' => 'A következő {days} napban az alábbi, még nem teljesített beadandóid járnak le:',
    'Solution last submitted at' => 'Utolsó próbálkozás ideje',
    'Status of latest submission' => 'Utolsó próbálkozás eredménye',
    'The table does not contain submissions you have already successfully completed.' => 'A sikeresen teljesített beadandókat a táblázat nem tartalmazza.',
    'Link to your CodeCompass instance: ' => 'A CodeCompass szerver elérhető itt: ',
    'Your username: {username}' => 'A felhasználóneved: {username}',
    'Your password: {password}' => 'A jelszavad: {password}',
    'CodeCompass started' => 'CodeCompass elindult',
    'Your requested CodeCompass instance has now been started for the solution of {name} course: {course}.' => 'A korábban kért CodeCompass szerver elindult. Hallgató: {name}, kurzus: {course}.',
    'Notes' => 'Megjegyzések',
    'New notes were added' => 'Új megjegyzések lettek hozzáadva',
    'New Notes' => 'Új megjegyzések',
    'Static code analysis ready' => 'A statikus kódanalízis elkészült',
    'Static code analysis on your previously submitted solution is ready.' => 'A statikus kódanalízis elkészült a beküldött megoldáshoz.',
    'No issues were found in the uploaded submission.' => 'Nem találhatóak problémák a feltölött megoldásban.',
    'The static analyzer tool failed to run. The uploaded solution may be incorrect or the configuration for the task may be invalid.'
        => 'A statikus elemző futtatása sikertelen volt. Előfordulhat hogy hibás a feltölött megoldás vagy érvénytelen a feladathoz tartozó konfiguráció.',
    'Reports' => 'Jelentések',
    'File (line, column)' => 'Fájl (sor, oszlop)',
    'Checker' => 'Ellenőrző',
    'Severity' => 'Súlyosság',
    'Message' => 'Üzenet'
];
