<?php

return [
    'group1' => [
        'id' => 2000,
        'courseID' => 4000,
        'semesterID' => 3001,
        'number' => 1,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group2' => [
        'id' => 2001,
        'courseID' => 4002,
        'semesterID' => 3001,
        'number' => 2,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group3' => [
        'id' => 2002,
        'courseID' => 4000,
        'semesterID' => 3001,
        'number' => 3,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    "group4" => [
        'id' => 2003,
        'courseID' => 4000,
        'semesterID' => 3001,
        'number' => 4,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group5' => [
        'id' => 2004,
        'courseID' => 4000,
        'semesterID' => 3001,
        'number' => 5,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group6_canvas' => [
        'id' => 2005,
        'courseID' => 4000,
        'semesterID' => 3001,
        'number' => 6,
        'isExamGroup' => 0,
        'canvasCourseID' => 1,
        'timezone' => 'Europe/Budapest',
    ],
    'group7' => [
        'id' => 2006,
        'courseID' => 4001,
        'semesterID' => 3001,
        'number' => 7,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group8' => [
        'id' => 2007,
        'courseID' => 4001,
        'semesterID' => 3001,
        'number' => 8,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group9' => [
        'id' => 2008,
        'courseID' => 4001,
        'semesterID' => 3000,
        'number' => 9,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group10' => [
        'id' => 2009,
        'courseID' => 4001,
        'semesterID' => 3000,
        'number' => 10,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
    'group11' => [
        'id' => 2010,
        'courseID' => 4002,
        'semesterID' => 3000,
        'number' => 11,
        'isExamGroup' => 0,
        'timezone' => 'Europe/Budapest',
    ],
];
