<?php

return [
    'file1_upload_log1' => [
        'id' => 1,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 1,
    ],
    'file2_upload_log1' => [
        'id' => 2,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 2,
    ],
    'file3_upload_log1' => [
        'id' => 3,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 3,
    ],
    'file4_upload_log1' => [
        'id' => 4,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 4,
    ],
    'file5_upload_log1' => [
        'id' => 5,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 5,
    ],
    'file6_upload_log1' => [
        'id' => 6,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 6,
    ],
    'file7_upload_log1' => [
        'id' => 7,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 7,
    ],
    'file8_upload_log1' => [
        'id' => 8,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 8,
    ],
    'file9_upload_log1' => [
        'id' => 9,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 9,
    ],
    'file10_upload_log1' => [
        'id' => 10,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 10,
    ],
    'file11_upload_log1' => [
        'id' => 11,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 11,
    ],
    'file12_upload_log1' => [
        'id' => 12,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 12,
    ],
    'file13_upload_log1' => [
        'id' => 13,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 13,
    ],
    'file14_upload_log1' => [
        'id' => 14,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 14,
    ],
    'file15_upload_log1' => [
        'id' => 15,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.2',
        'submissionID' => 15,
    ],
    'file16_upload_log1' => [
        'id' => 16,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 16,
    ],
    'file16_upload_log2' => [
        'id' => 17,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-4 minute')),
        'ipAddress' => '192.168.1.2',
        'submissionID' => 16,
    ],
    'file16_upload_log3' => [
        'id' => 18,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-3 minute')),
        'ipAddress' => '192.168.1.2',
        'submissionID' => 16,
    ],
    'file16_upload_log4' => [
        'id' => 19,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-2 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 16,
    ],
    'file16_upload_log5' => [
        'id' => 20,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'ipAddress' => '192.168.1.3',
        'submissionID' => 16,
    ],
    'file33_upload_log1' => [
        'id' => 21,
        'activity' => \app\models\IpAddress::ACTIVITY_SUBMISSION_UPLOAD,
        'logTime' => date('Y-m-d H:i:s', strtotime('-3 minute')),
        'ipAddress' => '192.168.1.1',
        'submissionID' => 34,
    ],
];
