<?php

return [
    'plagiarism1' => [
        'id' => 1,
        'token' => null,
        'requesterID' => 1006,
        'semesterID' => 3001,
        'taskIDs' => '',
        'userIDs' => '',
        'name' => 'plagiarism1',
        'description' => 'description1',
        'response' => null,
        'ignoreThreshold' => 10,
        'baseFileIDs' => '',
    ],
    'plagiarism2' => [
        'id' => 2,
        'token' => null,
        'requesterID' => 1007,
        'semesterID' => 3000,
        'taskIDs' => '',
        'userIDs' => '',
        'name' => 'plagiarism2',
        'description' => 'description2',
        'response' => null,
        'ignoreThreshold' => 10,
        'baseFileIDs' => '',
    ],
    'plagiarism3' => [
        'id' => 3,
        'token' => null,
        'requesterID' => 1007,
        'semesterID' => 3001,
        'taskIDs' => '5000,5001',
        'userIDs' => '1001,1002',
        'name' => 'plagiarism3',
        'description' => 'description3',
        'response' => null,
        'ignoreThreshold' => 5,
        'baseFileIDs' => '',
    ],
    'plagiarism4' => [
        'id' => 4,
        'token' => null,
        'requesterID' => 1007,
        'semesterID' => 3001,
        'taskIDs' => '5000,5001',
        'userIDs' => '1001,1002,1003',
        'name' => 'plagiarism4',
        'description' => 'description4',
        'response' => null,
        'ignoreThreshold' => 10,
        'baseFileIDs' => '',
    ],
    'plagiarism5' => [
        'id' => 5,
        'token' => null,
        'requesterID' => 1006,
        'semesterID' => 3001,
        'taskIDs' => '5001',
        'userIDs' => '1001,1002,1003',
        'name' => 'plagiarism5',
        'description' => 'description5',
        'response' => null,
        'ignoreThreshold' => 10,
        'baseFileIDs' => '',
    ],
    'plagiarism6' => [
        'id' => 6,
        'token' => null,
        'requesterID' => 1006,
        'semesterID' => 3001,
        'taskIDs' => '5009',
        'userIDs' => '1001,1002,1003',
        'name' => 'plagiarism6',
        'description' => 'description6',
        'response' => "http://moss.stanford.edu/results/0/12345689\n",
        'ignoreThreshold' => 10,
        'baseFileIDs' => '',
    ],
    'plagiarism7' => [
        'id' => 7,
        'token' => 'ad9e9bcd00632c86b547a1db0f3c9502',
        'requesterID' => 1006,
        'semesterID' => 3001,
        'taskIDs' => '5009',
        'userIDs' => '1001,1002,1003',
        'name' => 'plagiarism7',
        'description' => 'description7',
        'response' => "http://moss.stanford.edu/results/0/12345689\n",
        'ignoreThreshold' => 10,
        'baseFileIDs' => '6000',
    ],
];
