<?php

return [
    'file1' => [
        'id' => 1,
        'name' => 'stud01.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '2',
        'uploaderID' => '2',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_LATE_SUBMISSION,
        'isVersionControlled' => 0,
        'grade' => 4,
        'notes' => '',
        'graderID' => '8',
        'errorMsg' => 'FULL_ERROR_MESSAGE',
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_COMPILATION_FAILED,
    ],
    'file2' => [
        'id' => 2,
        'name' => 'stud02.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '2',
        'uploaderID' => '3',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_LATE_SUBMISSION,
        'isVersionControlled' => 0,
        'grade' => '',
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
    'file3' => [
        'id' => 3,
        'name' => 'stud01.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '3',
        'uploaderID' => '2',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_ACCEPTED,
        'isVersionControlled' => 0,
        'grade' => 5,
        'notes' => '',
        'graderID' => '8',
        'errorMsg' => 'FULL_ERROR_MESSAGE',
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_COMPILATION_FAILED,
    ],
    'file4' => [
        'id' => 4,
        'name' => 'stud02.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '3',
        'uploaderID' => '3',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_REJECTED,
        'isVersionControlled' => 0,
        'grade' => '1',
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
    'file5' => [
        'id' => 5,
        'name' => 'stud01.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '8',
        'uploaderID' => '2',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_UPLOADED,
        'isVersionControlled' => 0,
        'grade' => '',
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
    'file6' => [
        'id' => 6,
        'name' => 'stud01.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '5',
        'uploaderID' => '2',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_UPLOADED,
        'isVersionControlled' => 0,
        'grade' => '',
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
    'file7' => [
        'id' => 7,
        'name' => 'stud01.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '6',
        'uploaderID' => '2',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_UPLOADED,
        'isVersionControlled' => 0,
        'grade' => '',
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
    'file8' => [
        'id' => 8,
        'name' => 'stud03.zip',
        'uploadTime' => date('Y-m-d H:i:s', strtotime('-5 minute')),
        'taskID' => '2',
        'uploaderID' => '4',
        'isAccepted' => \app\models\StudentFile::IS_ACCEPTED_UPLOADED,
        'isVersionControlled' => 0,
        'grade' => 4,
        'notes' => '',
        'errorMsg' => null,
        'evaluatorStatus' => \app\models\StudentFile::EVALUATOR_STATUS_NOT_TESTED,
    ],
];
