<?php

return [
    'task1' => [
        'id' => 5000,
        'name' => 'Task 1',
        'semesterID' => 3001,
        'groupID' => 2000,
        'hardDeadline' => '2021-03-08 10:00:00',
        'category' => 'Larger tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
        'codeCompassCompileInstructions' => 'sudo magic compile command',
        'codeCompassPackagesInstallInstructions' => 'apt-get install qt5 wireshark -y'
    ],
    'task2' => [
        'id' => 5001,
        'name' => 'Task 2',
        'semesterID' => 3001,
        'groupID' => 2000,
        'softDeadLine' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'category' => 'Smaller tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 1,
        'showFullErrorMsg' => 0,
    ],
    'task3' => [
        'id' => 5002,
        'name' => 'Task 3',
        'semesterID' => 3001,
        'groupID' => 2000,
        'softDeadLine' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Larger tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 1,
        'showFullErrorMsg' => 1,
    ],
    'task4' => [
        'id' => 5003,
        'name' => 'Task 4',
        'semesterID' => 3001,
        'groupID' => 2000,
        'available' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'category' => 'Exams',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
    ],
    'task5' => [
        'id' => 5004,
        'name' => 'Task 5',
        'semesterID' => 3001,
        'groupID' => 2001,
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Classwork tasks',
        'description' => 'Description',
        'createrID' => 1006,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
    ],
    'task6' => [
        'id' => 5005,
        'name' => 'Task 6',
        'semesterID' => 3000,
        'groupID' => 2010,
        'hardDeadline' => '2020-12-08 10:00:00',
        'available' => null,
        'category' => 'Classwork tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
    ],
    'task7_canvas' => [
        'id' => 5006,
        'name' => 'Task 7',
        'semesterID' => 3001,
        'groupID' => 2005,
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Canvas tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
        'canvasID' => 2,
    ],
    'task8' => [
        'id' => 5007,
        'name' => 'Task 8',
        'semesterID' => 3001,
        'groupID' => 2007,
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Smaller tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
    ],
    'task9' => [
        'id' => 5008,
        'name' => 'Task 9',
        'semesterID' => 3001,
        'groupID' => 2000,
        'softDeadLine' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Larger tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
        'autoTest' => 0,
        'showFullErrorMsg' => 0,
    ],
    'task10' => [
        'id' => 5009,
        'name' => 'Task 10',
        'semesterID' => 3001,
        'groupID' => 2000,
        'softDeadLine' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'hardDeadline' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'available' => null,
        'category' => 'Larger tasks',
        'description' => 'Description',
        'createrID' => 1007,
        'isVersionControlled' => 0,
    ],
];
