<?php

return [
    'testinstance1' => [
        'id' => 1,
        'submitted' => 1,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 3,
        'testID' => 1,
    ],
    'testinstance2' => [
        'id' => 2,
        'submitted' => 0,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 2,
        'testID' => 1,
    ],
    'testinstance3' => [
        'id' => 3,
        'submitted' => 0,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 3,
        'testID' => 1,
    ],
    'testinstance4' => [
        'id' => 4,
        'submitted' => 0,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 3,
        'testID' => 1,
    ],
    'testinstance5' => [
        'id' => 5,
        'submitted' => 1,
        'starttime' => date('Y-m-d H:i:s'),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 3,
        'testID' => 1,
    ],
    'testinstance6' => [
        'id' => 6,
        'submitted' => 1,
        'starttime' => date('Y-m-d H:i:s'),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 3,
        'testID' => 7,
    ],
    'testinstance7' => [
        'id' => 7,
        'submitted' => 0,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 3,
        'testID' => 7,
    ],
    'testinstance8' => [
        'id' => 8,
        'submitted' => 0,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 3,
        'testID' => 8,
    ],
    'testinstance9' => [
        'id' => 9,
        'submitted' => 0,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 3,
        'testID' => 1,
    ],
];
