<?php

return [
    'testinstance1' => [
        'id' => 1,
        'submitted' => true,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 1002,
        'testID' => 1,
    ],
    'testinstance2' => [
        'id' => 2,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1001,
        'testID' => 1,
    ],
    'testinstance3' => [
        'id' => 3,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 1,
    ],
    'testinstance4' => [
        'id' => 4,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 1,
    ],
    'testinstance5' => [
        'id' => 5,
        'submitted' => true,
        'starttime' => date('Y-m-d H:i:s'),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 1002,
        'testID' => 1,
    ],
    'testinstance6' => [
        'id' => 6,
        'submitted' => true,
        'starttime' => date('Y-m-d H:i:s'),
        'finishtime' => date('Y-m-d H:i:s', time() + 120),
        'score' => 0,
        'userID' => 1002,
        'testID' => 7,
    ],
    'testinstance7' => [
        'id' => 7,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 7,
    ],
    'testinstance8' => [
        'id' => 8,
        'submitted' => false,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 8,
    ],
    'testinstance9' => [
        'id' => 9,
        'submitted' => false,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 1,
    ],
    'testinstance10' => [
        'id' => 10,
        'submitted' => false,
        'starttime' => date('Y-m-d H:i:s', time() + 240),
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 13,
    ],
    'testinstance11' => [
        'id' => 11,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 14,
    ],
    'testinstance12' => [
        'id' => 12,
        'submitted' => false,
        'starttime' => null,
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'token' => "STUD02;VALID",
        'testID' => 14,
    ],
    'testinstance13' => [
        'id' => 13,
        'submitted' => false,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 1002,
        'testID' => 14,
    ],
    'testinstance14' => [
        'id' => 14,
        'submitted' => false,
        'starttime' => date('Y-m-d H:i:s', strtotime('-1 minute')),
        'finishtime' => null,
        'score' => 0,
        'userID' => 1003,
        'testID' => 14,
    ],
];
