<?php

return [
    'test' => [
        'id' => 1,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'invalid1' => [
        'id' => 2,
        'name' => 'Test',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'invalid3' => [
        'id' => 4,
        'name' => 'Test',
        'questionamount' => 5,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'invalid4' => [
        'id' => 5,
        'name' => 'Test',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'invalid5' => [
        'id' => 6,
        'name' => 'Test',
        'questionamount' => 1,
        'duration' => 172800, //2 days
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' =>  date('Y-m-d H:i:s', strtotime('-1 hour')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'testNotAvailable' => [
        'id' => 7,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('-1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'testAvailable' => [
        'id' => 8,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 0,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'testAvailable1' => [
        'id' => 9,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('-2 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'questionsetID' => 1,
        'groupID' => 2,
    ],
    'testFixed' => [
        'id' => 10,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 30,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => "2021-02-01 10:00:00",
        'availableuntil' => "2021-02-01 11:00:00",
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'testWithoutEnoughtQuestions' => [
        'id' => 11,
        'name' => 'Vizsga',
        'questionamount' => 100,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
    'testEmptyGroup' => [
        'id' => 12,
        'name' => 'Vizsga',
        'questionamount' => 1,
        'duration' => 30,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => "2021-02-01 10:00:00",
        'availableuntil' => "2021-02-01 11:00:00",
        'questionsetID' => 1,
        'groupID' => 7,
    ],
    'testFuture' => [
        'id' => 13,
        'name' => 'Vizsga',
        'questionamount' => 100,
        'duration' => 110,
        'shuffled' => 1,
        'unique' => 1,
        'availablefrom' => date('Y-m-d H:i:s', strtotime('+1 day')),
        'availableuntil' => date('Y-m-d H:i:s', strtotime('+2 day')),
        'questionsetID' => 1,
        'groupID' => 1,
    ],
];
